### PR TITLE
ARGO-416 Centralize authentication / Refactor Routing

### PR DESCRIPTION
**Pull request by kaggis**
### Goal 
Implement central authentication handling 

### Challenges 
 - Main routing + subrouting declaration on each package
 - Respond Handler not robust enough to create a handler chain 
 - Authentication calls on all HandleFunctions in all packages 
 - After tenant user authentication, tenantDBConfiguration must be forwared down the handler chain
 - Each package has repeating method declarations on subrouters. Needs to be automated in order to be able to easily use WrapHandlers in one place (and not on each route declaration)
 - To achieve the above Routing on ./app/ packages needs to be refactored
 
#### App package Routing refactoring
 - Declare AppRoute util structure centrally to describe app subroutes 
 - Declare PrepAppRoutes func centrally to use it to automatically build subrouters
  - PrepAppRoutes gets a mux.router + a list of AppRoutes and prepares a subrouter
 - Replace explicit subroute definitions with automatic subrouter creation on all App packages (reports,profiles,results,statuses,recomputations,tenants etc...)

#### Central Authentication 
 - Use a WrapAuthentication handle wrapper 
 - Check if request needs API Admin auth or TENANT User auth and act accordingly 
 - Use context to forward tenant db configuration in handler chain 
 - If authentication problem immediately call respond.Error handle func wich actually handles error responses in one place. Use error enumerations to quickly reference and create error responses

#### Implementation Details

- [x] Introduce boilerplate handle wrappers in `./respond/wrappers.go`
 - [x] wrapper placeholder for authentication
 - [x] wrapper placeholder for authorization
 - [x] wrapper placeholder for validation
- [x] Introduce WrapAll to wrap all available handle wrappers at once (forming a chain)
- [x] Use WrapAll in `reports`,`aggregationProfiles`,`metricProfiles`,`operationsProfiles` pkg routings
- [x] Move tenant authentication logic inside WrapAuthentication
- [x] Use central tenant authentication on all packages
- [x] Use admin central authentication on tenant package 
- [x] Refactor Subrouting in packages
 - [x] use AppRoutes and PrepAppRoutes to automatically define subrouters
 - [x] Replace routing definitions on all packages

### CODE REVIEW

**Comment by kaggis** [comment]
please review
/cc @pkoro @themiszamani @skanct

**Comment by themiszamani** [comment]
+1 remove the commetns from routes with a different subrouter

**Comment by pkoro** [comment]
@kaggis I see you remove some imports from under godep. Is this intentional? Other than this +1 from me.

**Comment by pkoro** [comment]
+1

**Pull request merged**
