### PR TITLE
ARGO-219 Status endpoints updates

### PR DESCRIPTION
**Pull request by pkoro**

### CODE REVIEW

**Comment by pkoro** [comment]
please review /cc @kaggis

**Comment by pkoro** [comment]
This PR fixes two issues:

1) the `date_int` field inside the model is changes to `date_integer` to match with the incoming output fmor the compute engine

2) the xml and json responses are changed in order not to refer to the endpoint level as a group. For brevity this is the change in the xml response case:

from 

```
 <root>
   <group name="HG-03-AUTH" type="SITES">
     <group name="CREAM-CE" type="service">
       <group name="cream01.afroditi.gr" type="endpoint">
         <status timestamp="2015-05-01T00:00:00Z" value="OK"></status>
         <status timestamp="2015-05-01T01:00:00Z" value="CRITICAL"></status>
         <status timestamp="2015-05-01T05:00:00Z" value="OK"></status>
       </group>
     </group>
   </group>
 </root>
```

to 

```
 <root>
   <group name="HG-03-AUTH" type="SITES">
     <group name="CREAM-CE" type="service">
       <endpoint name="cream01.afroditi.gr">
         <status timestamp="2015-05-01T00:00:00Z" value="OK"></status>
         <status timestamp="2015-05-01T01:00:00Z" value="CRITICAL"></status>
         <status timestamp="2015-05-01T05:00:00Z" value="OK"></status>
       </endpoint>
     </group>
   </group>
 </root>
```

**Comment by pkoro** [comment]
please review /cc @kaggis @dpavlos @skanct

**Comment by kaggis** [comment]
+1

**Pull request merged**
