### PR TITLE
ARGO-300 CORS support and addition of OPTIONS verb in resources

### PR DESCRIPTION
**Pull request by pkoro**
# Description

Changes needed in order to allow "Try it Out!" swagger-ui button to work as expected. 

## CORS support
- [x] CORS fine-tuning & configuration details (TBD)

## Add OPTIONS verb for API resources
 - [x] aggregationProfiles
 - [x] factors
 - [x] metricProfiles
 - [x] operationsProfiles
 - [x] reports
 - [x] results
 - [x] statusEndpointGroups
 - [x] statusEndpoints
 - [x] statusMetrics
 - [x] statusServices
 - [x] tenants

### CODE REVIEW

**Comment by pkoro** [comment]
This PR is ready. The CORS stuff is by default disabled on the API, hence in general we can enable it (via the configuration file) just in the case for swagger. 

The OPTIONS verb is properly supported via this PR on all required API resources. In specific the API responds with an empty body, a 200 (OK) code and an `Allow` header which includes in a comma separated list the allowed verbs for the given resource. 

I have not squashed the commits yet, but let me know if you want me to do so beforehand. 

please review /cc @kaggis @skanct @themiszamani

**Comment by pkoro** [comment]
please review /cc @skanct

**Comment by skanct** [comment]
Two comments from my side:

1. Why you set the content-type to html, while everywhere else we use either application/json or application/xml
2. The specification says: 

  > A server MUST generate a Content-Length field with a value of "0" if no payload body is to be sent in the response.

   Is the Content-Length properly generated?

**Comment by themiszamani** [comment]
+1

**Pull request merged**
