### PR TITLE
ARGO-104 Update github remote paths to be consistent with the repo name changes

### PR DESCRIPTION
**Pull request by dpavlos**
* Updated import statements.
* Spec,Makefile,conf and README need also to be updated

### CODE REVIEW

**Comment by dpavlos** [comment]
All modifications have been completed.
Please review /cc @pkoro @skanct @makistsantekidis

**Comment by pkoro** [comment]
+1 (although my judgement is biased)

**Comment by pkoro** [comment]
Just also to add a note I neglected to make.This merge will induce some work on the developers workspaces. For example `go get` now creates under `$GOPATH/src/...` a `ar-web-api` folder (as this is how it is referenced in the import statements. After merging and syncing this path will be altered to `argo-web-api`. I am just making the note for clarity primarily. I don't think this is something that should block us.

**Comment by makistsantekidis** [comment]
+1 tests pass and installation does not try to retrieve ar-web-api.

**Pull request merged**
