### PR TITLE
ARGO-213 Status metrics

### PR DESCRIPTION
**Pull request by pkoro**
please review /cc @kaggis

### CODE REVIEW

**Comment by pkoro** [comment]
This commit fixes ARGO-213 and part of ARGO-219. The other part of the latter is in #129. 

Wrt ARGO-219 as an example the xml reponse is changed from

```
 <root>
   <group name="HG-03-AUTH" type="SITES">
     <group name="CREAM-CE" type="service">
       <group name="cream01.afroditi.gr" type="endpoint">
         <group name="emi.cream.CREAMCE-JobSubmit" type="metric">
           <status timestamp="2015-04-30T23:59:00Z" value="OK"></status>
           <status timestamp="2015-05-01T00:00:00Z" value="OK"></status>
           <status timestamp="2015-05-01T01:00:00Z" value="CRITICAL"></status>
           <status timestamp="2015-05-01T05:00:00Z" value="OK"></status>
         </group>
       </group>
     </group>
   </group>
 </root>
```

to 

```
 <root>
   <group name="HG-03-AUTH" type="SITES">
     <group name="CREAM-CE" type="service">
       <endpoint name="cream01.afroditi.gr">
         <metric name="emi.cream.CREAMCE-JobSubmit">
           <status timestamp="2015-04-30T23:59:00Z" value="OK"></status>
           <status timestamp="2015-05-01T00:00:00Z" value="OK"></status>
           <status timestamp="2015-05-01T01:00:00Z" value="CRITICAL"></status>
           <status timestamp="2015-05-01T05:00:00Z" value="OK"></status>
         </metric>
       </endpoint>
     </group>
   </group>
 </root>
```

**Comment by pkoro** [comment]
please review /cc @dpavlos

**Comment by pkoro** [comment]
please review (someone) /cc @skanct @kaggis @dpavlos @makistsantekidis

**Comment by kaggis** [comment]
+1

**Pull request merged**
